#!/bin/sh
mkdir -p dist
NODE_ENV=production node_modules/.bin/browserify ./index.js -t browserify-shim -t envify --detect-globals false -s ReactTokenInput > dist/react-tokeninput.js
node_modules/.bin/uglifyjs dist/react-tokeninput.js --compress warnings=false > dist/react-tokeninput.min.js
